{ config, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = "mocha";
  home.homeDirectory = "/home/mocha";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "25.05"; # Please read the comment before changing.

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = [
    # # Adds the 'hello' command to your environment. It prints a friendly
    # # "Hello, world!" when run.
    # pkgs.hello

    # # It is sometimes useful to fine-tune packages, for example, by applying
    # # overrides. You can do that directly here, just don't forget the
    # # parentheses. Maybe you want to install Nerd Fonts with a limited number of
    # # fonts?
    # (pkgs.nerdfonts.override { fonts = [ "FantasqueSansMono" ]; })

    # # You can also create simple shell scripts directly inside your
    # # configuration. For example, this adds a command 'my-hello' to your
    # # environment:
    # (pkgs.writeShellScriptBin "my-hello" ''
    #   echo "Hello, ${config.home.username}!"
    # '')

    pkgs.btop
    pkgs.fuzzel
    pkgs.wallust
    pkgs.swww

    pkgs.lazygit
    pkgs.delta
    pkgs.zoxide

    pkgs.file
    pkgs.eza
    pkgs.bat
    pkgs.fd
    pkgs.fzf
    pkgs.ripgrep
    pkgs.tldr

    pkgs.vesktop
    pkgs.prismlauncher
  ];

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';

    # ".config/nvim".source = ~/dotfiles/nvim;

    ".gitconfig".source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/git/.gitconfig";
    ".zshrc.ext".source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/zsh/.zshrc";
    ".config/kitty".source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/kitty";
    ".config/swww".source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotfiles/swww";
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. These will be explicitly sourced when using a
  # shell provided by Home Manager. If you don't want to manage your shell
  # through Home Manager then you have to manually source 'hm-session-vars.sh'
  # located at either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/mocha/etc/profile.d/hm-session-vars.sh
  #
  home.sessionVariables = {
    # EDITOR = "emacs";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  programs.zsh = {
    enable = true;
    initContent = ''
      source ~/.zshrc.ext
    '';
  };

  programs.neovim = {
    enable = true;
    # plugins = with pkgs.vimPlugins; [
    #   lazyNixHelper
    # ];

    extraLuaConfig = ''
      -- THIS PLUGIN LIST SHOULD BE GENERATED BY YOUR NIX CONFIG. See the NixOS Configuration section for more details on plugins table and lazy_nix_helper_path
      -- local plugins = {
      --   ["plugin-name.nvim"] = "nix/store/hash1234-vimplugin-plugin-name.nvim",
      -- }
      
      local lazy_nix_helper_path = {<lazy-nix-helper/nix/store/path>}
      
      -- if we are not on a nix-based system, bootstrap lazy_nix_helper in the same way lazy is bootstrapped
      if not vim.loop.fs_stat(lazy_nix_helper_path) then
        lazy_nix_helper_path = vim.fn.stdpath("data") .. "/lazy_nix_helper/lazy_nix_helper.nvim"
        if not vim.loop.fs_stat(lazy_nix_helper_path) then
          vim.fn.system({
            "git",
            "clone",
            "--filter=blob:none",
            "https://github.com/b-src/lazy_nix_helper.nvim.git",
            lazy_nix_helper_path,
          })
        end
      end
      
      -- add the Lazy-Nix-Helper plugin to the vim runtime
      vim.opt.rtp:prepend(lazy_nix_helper_path)
      
      -- call the Lazy-Nix-Helper setup function. pass a default lazypath for non-nix systems as an argument
      local non_nix_lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
      require("lazy-nix-helper").setup({ lazypath = non_nix_lazypath, input_plugin_table = plugins })
      
      -- get the lazypath from Lazy-Nix-Helper
      local lazypath = require("lazy-nix-helper").lazypath()
      -- the rest of the configuration is unchanged
      if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({
          "git",
          "clone",
          "--filter=blob:none",
          "https://github.com/folke/lazy.nvim.git",
          "--branch=stable", -- latest stable release
          lazypath,
        })
      end
      -- add the Lazy plugin to the vim runtime
      vim.opt.rtp:prepend(lazypath)
      
      -- set mapleader before loading lazy if applicable
      vim.g.mapleader = " "
      
      -- install and load plugins from your configuration
      require("lazy").setup(plugins, opts)
    '';
  };

  systemd.user.services.swww-daemon = {
    Unit = {
      Description = "swww daemon";
      After = [ "xdg-desktop-autostart.target" ];
    };
    Service.ExecStart = "${pkgs.swww}/bin/swww-daemon";
    Install.WantedBy = [ "default.target" ];
  };
}
