#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b
wal -R
xinput set-prop "pointer:Razer Razer DeathAdder Elite" "libinput Accel Speed" -1

bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config normal_border_color     "$color1"
bspc config active_border_color     "$color2"
bspc config focused_border_color    "$color15"
bspc config presel_feedback_color   "$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
