#!/bin/sh

# Backgroud process initialization
pgrep -x sxhkd > /dev/null || sxhkd &
wal -R
$HOME/.fehbg
picom &
# $HOME/.config/polybar/launch.sh

# Monitor setup
bspc monitor -d I II III IV V VI VII VIII IX X

# Window configuration
bspc config border_width         2
bspc config window_gap           4

# Monocle mode (focus window)
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
