#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"

xinput set-prop "pointer:Razer Razer DeathAdder Elite" "libinput Accel Speed" -1
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b
wal -R
$HOME/.config/polybar/launch.sh

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
# Α Β Γ Δ Ε Ζ Η Θ Ι Κ
# a b c d e f g h i j
# 1 2 3 4 5 6 7 8 9 10

bspc config border_width            2
bspc config window_gap              6

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config normal_border_color     "$color1"
bspc config active_border_color     "$color2"
bspc config focused_border_color    "$color15"
bspc config presel_feedback_color   "$color1"

bspc rule -a discord desktop=^10 state=fullscreen
